###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "nomad",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "nomad",
    "password": "12345"
}

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "comad",
    "password": "salainen"
}
