###
# Create a user
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "comad@foppi.com",
    "name": "Comad"
}


###
# Try login with non existen user
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "nomad",
    "password": "salainen"
}

###
# Login with existing user, but wrong password
# Note: you need to create the user using the first
# request
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "comad@foppi.com",
    "password": "12345"
}

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "comad@foppi.com",
    "password": "salainen"
}
