###
POST http://localhost:3001/api/readinglists HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vbWFkMkBrb3BwaS5jb20iLCJpZCI6MSwiaWF0IjoxNjc5OTAwNTgxfQ.K4dCYmOPRFL2VOHm0acfk2Rol1q2YjIwImIGBmF7J9I

{
    "blogId": "1",
    "userId": "1"
}

###
PUT http://localhost:3001/api/readinglists/2 HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vbWFkMkBrb3BwaS5jb20iLCJpZCI6NywiaWF0IjoxNjgwMDEwNTA1fQ.xd-tQhddUHicKsaC7BRL6YyKmYF5DHfRF_GEHVyUajo

{
    "read": true
}
