###
# Adding to users reading list
POST http://localhost:3001/api/readinglists HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbWFkQGZvcHBpLmNvbSIsImlkIjoyLCJpYXQiOjE2ODAxNzYwMzh9.v0Ik8uRcQlE7BZkzVRPTeiFL11VctXtL17pBRFTK1i0

{
    "blogId": "4",
    "userId": "2"
}

###
# Changing status to read
PUT http://localhost:3001/api/readinglists/1 HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbWFkQGZvcHBpLmNvbSIsImlkIjoyLCJpYXQiOjE2ODAxNzYwMzh9.v0Ik8uRcQlE7BZkzVRPTeiFL11VctXtL17pBRFTK1i0

{
    "read": true
}


###
# Get a single user
GET http://localhost:3001/api/users/2?read=true HTTP/1.1

###
# Get a single user
GET http://localhost:3001/api/users/2?read=false HTTP/1.1

###
# Get a single user
GET http://localhost:3001/api/users/2 HTTP/1.1
